Введите seed и создайте вектор размера 16 из целых случайных чисел в диапазоне от 0 до 10 включительно. Измените форму вектора на матрицу 4х4. Найдите и выведите на экран сумму чисел, стоящих на главной диагонали.

In [2]:
import numpy as np

seed = 42
np.random.seed(seed)

In [3]:
vector = np.random.randint(0, 11, size=16)


matrix = vector.reshape(4, 4)

diagonal_sum = np.trace(matrix)

print(diagonal_sum)

29


Введите seed и создайте вектор размера 10 из целых случайных чисел в диапазоне от 0 до 100. Введите любое целое число num и выведите ближайшее к нему число из массива. Цикл for не использовать!

In [4]:
vector = np.random.randint(0, 101, size=10)

num = 40
nearest_value = vector[np.abs(vector - num).argmin()]

print(nearest_value)

37


Введите целое число number и создайте numpy массив из целых чисел от 1 до number включительно. Добавьте три нуля между каждыми соседними элементами массива. Выведите результирующий массив на экран.

In [5]:
number = 3

array = np.arange(1, number + 1)
result = np.zeros(len(array) + 3 * (len(array) - 1), dtype=int)
result[::4] = array


print(result)

[1 0 0 0 2 0 0 0 3]


Напишите функцию add_one(ind), которая добавляет единицу к элементам вектора, состоящего из нулей, чей индекс указан в векторе ind. Функция выводит полученный вектор на экран. Цикл for не использовать!

In [13]:
def add_one(ind):
    size = np.max(ind) + 1
    vector = np.zeros(size, dtype=int)
    
    np.add.at(vector, ind, 1)
    
    print(vector)

In [14]:
ind = np.array([1, 2, 2])
add_one(ind)

[0 1 2]


In [15]:
ind = np.array([1, 2, 3, 4, 6])
add_one(ind)

[0 1 1 1 1 0 1]
